version: '2'

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:13.4-alpine
    container_name: db_whodat_container
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: trade
#      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./db/init-sql/:/docker-entrypoint-initdb.d/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
