version: '2'

networks:
  custom_network:
    driver: bridge

volumes:
  postgres:
    driver: local

services:
  db:
    container_name: db_whodat_container
    image: postgres:13.4-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: trade
#      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./db/init-sql/:/docker-entrypoint-initdb.d/
    networks:
      - custom_network
